### ISSUE TITLE
TypeError: Cannot set property length of [object Object] which has only a getter

### ISSUE THREAD

**Issue by karlingen** [gizur/github-issues-export#11]
Installation: 
```
$ npm install
```

Usage:
```
$ ./export-issues.js --user karlingen --password some_password --owner karlingen --repo myPrivateRepo --state open
```

Output:

```
/Users/derp/Desktop/github-issues-export-master/node_modules/jsdom/lib/jsdom/level1/core.js:554
      Array.prototype.splice.call(this._childNodes, refChildIndex, 0, newChild
                             ^
TypeError: Cannot set property length of [object Object] which has only a getter
    at Object.core.Node.insertBefore (/Users/derp/Desktop/github-issues-export-master/node_modules/jsdom/lib/jsdom/level1/core.js:554:30)
    at Object.<anonymous> (/Users/derp/Desktop/github-issues-export-master/node_modules/jsdom/lib/jsdom/level2/events.js:314:20)
    at Object.proto.(anonymous function) [as insertBefore] (/Users/derp/Desktop/github-issues-export-master/node_modules/jsdom/lib/jsdom/utils.js:21:26)
    at Object.core.Node.appendChild (/Users/derp/Desktop/github-issues-export-master/node_modules/jsdom/lib/jsdom/level1/core.js:672:17)
    at /Users/derp/Desktop/github-issues-export-master/node_modules/jQuery/lib/node-jquery.js:1416:15
    at /Users/derp/Desktop/github-issues-export-master/node_modules/jQuery/lib/node-jquery.js:1686:3
    at create (/Users/derp/Desktop/github-issues-export-master/node_modules/jQuery/lib/node-jquery.js:9429:3)
    at /Users/derp/Desktop/github-issues-export-master/node_modules/jQuery/lib/node-jquery.js:9435:18
    at Object.<anonymous> (/Users/derp/Desktop/github-issues-export-master/node_modules/jQuery/lib/node-jquery.js:9437:2)
    at Module._compile (module.js:460:26)
```

**Comment by colmsjo** [comment]
What node version are you using?

**Comment by karlingen** [comment]
v0.12.6

**Comment by colmsjo** [comment]
Look like a problem in the dependency jsdom, try with an older node version. You could also try to use a newer version of jsdom (update package.json)

**Comment by tnrich** [comment]
tried with the newer version of jsdom and ran into errors, what version of node do you reccomend?

**Comment by tnrich** [comment]
node v0.10.40 works

**Comment by colmsjo** [comment]
Ok, v10.40 is sounds right (I haven't worked in this for a while).
