### ISSUE TITLE
js TypeError: Cannot set property length of [object Object] which has only a getter

### ISSUE THREAD

**Issue by mcking65** [gizur/github-issues-export#13]
Getting the following ...

$ node ./export-issues --owner w3c --repo aria-practices
C:\Users\mck\node_modules\jsdom\lib\jsdom\level1\core.js:554
      Array.prototype.splice.call(this._childNodes, refChildIndex, 0, newChild);
                             ^

TypeError: Cannot set property length of [object Object] which has only a getter
    at Object.core.Node.insertBefore (C:\Users\mck\node_modules\jsdom\lib\jsdom\level1\core.js:554:30)
    at Object.<anonymous> (C:\Users\mck\node_modules\jsdom\lib\jsdom\level2\events.js:314:20)
    at Object.proto.(anonymous function) [as insertBefore] (C:\Users\mck\node_modules\jsdom\lib\jsdom\utils.js:21:26)
    at Object.core.Node.appendChild (C:\Users\mck\node_modules\jsdom\lib\jsdom\level1\core.js:672:17)
    at C:\Users\mck\node_modules\jQuery\lib\node-jquery.js:1416:15
    at C:\Users\mck\node_modules\jQuery\lib\node-jquery.js:1686:3
    at create (C:\Users\mck\node_modules\jQuery\lib\node-jquery.js:9429:3)
    at C:\Users\mck\node_modules\jQuery\lib\node-jquery.js:9435:18
    at Object.<anonymous> (C:\Users\mck\node_modules\jQuery\lib\node-jquery.js:9437:2)
    at Module._compile (module.js:409:26)

mck@MCK--243 MINGW64 ~/node_modules/github-issues-export
$

**Comment by colmsjo** [comment]
Seams like a problem in jsdom so you need to contact them. I'd look into node versions also.
